### ISSUE TITLE
各ページのmeta修正

### ISSUE THREAD

**Issue by glatchika** [suginoki45/Glatch-Portfolio-v3.0#34]

**Comment by suginoki45** [comment]
## ◆全ページ
### og:url
×　https://gltachdesign.com
○　https://glatchdesign.com

### タイトル
BtoBのLP・コーポレートサイト制作なら | Glatch（グラッチ）- フリーランスユニット
↓
Glatch（グラッチ） - 夫婦で活動するフリーランスWeb制作ユニット


## ◆制作の流れ description
Glatch（グラッチ）にご依頼いただいた場合、ご発注いただいてから納品までの制作の流れをご紹介しています。
↓
Glatch（グラッチ）にご依頼いただいた場合の、お問い合わせいただいてから納品までのWebサイト制作の流れをご紹介しています。


## ◆ブログ記事ページ、制作実績詳細ページ
og:url  記事ページURLにしたい
og:image  記事のアイキャッチにしたい
og:type  articleにしたい
